
#    PRINT "DOWNLOAD ${COMPONENT} Content"
#    curl -s -L -o /tmp/${COMPONENT}.zip "https://github.com/roboshop-devops-project/${COMPONENT}/archive/main.zip" &>>${LOG}
#    CHECK_STAT $?
#    PRINT "clean old content"
#    cd /usr/share/nginx/html
#    rm -rf * &>>${LOG}
#    CHECK_STAT $?
#    PRINT "extract ${COMPONENT} content"
#    unzip /tmp/${COMPONENT}.zip  &>>${LOG}
#    CHECK_STAT $?
#    PRINT " ORGANISE ${COMPONENT}  CONTENT"
#    mv ${COMPONENT}-main/* . && mv static/* . && rm -rf ${COMPONENT}-main README.md && mv localhost.conf /etc/nginx/default.d/roboshop.conf
#
#    for backend in catalogue cart user shipping payment ; do
#    PRINT "Update Configuration for - $backend"
#    #sed -i -e '/catalogue/ s/localhost/catalogue.roboshop.internal/' -e '/user/ s/localhost/user.roboshop.internal/' -e '/cart/ s/localhost/cart.roboshop.internal/' -e '/payment/ s/localhost/payment.roboshop.internal/' -e '/shipping/ s/localhost/shipping.roboshop.internal/' /etc/nginx/default.d/roboshop.conf
#    sed -i -e "/$backend/ s/localhost/$backend.roboshop.internal/" /etc/nginx/default.d/roboshop.conf
#    CHECK_STAT $?
#    done
#    PRINT " START NGINX SERVICE "
#    systemctl enable nginx &>>${LOG} && systemctl restart nginx  &>>${LOG}
#    CHECK_STAT $?
#  }

- name: Installing Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Import data for {{ COMPONENT }}
  ansible.builtin.include_role:
    name: common
    tasks_from: download.yml

- name: Deleting old content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent
