
#    PRINT " ORGANISE ${COMPONENT}  CONTENT"
#    mv ${COMPONENT}-main/* . && mv static/* . && rm -rf ${COMPONENT}-main README.md && mv localhost.conf /etc/nginx/default.d/roboshop.conf
#
#    for backend in catalogue cart user shipping payment ; do
#    PRINT "Update Configuration for - $backend"
#    #sed -i -e '/catalogue/ s/localhost/catalogue.roboshop.internal/' -e '/user/ s/localhost/user.roboshop.internal/' -e '/cart/ s/localhost/cart.roboshop.internal/' -e '/payment/ s/localhost/payment.roboshop.internal/' -e '/shipping/ s/localhost/shipping.roboshop.internal/' /etc/nginx/default.d/roboshop.conf
#    sed -i -e "/$backend/ s/localhost/$backend.roboshop.internal/" /etc/nginx/default.d/roboshop.conf
#    CHECK_STAT $?
#    done
#    PRINT " START NGINX SERVICE "
#    systemctl enable nginx &>>${LOG} && systemctl restart nginx  &>>${LOG}
#    CHECK_STAT $?
#  }

- name: Installing Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Import data for {{ COMPONENT }}
  ansible.builtin.include_role:
    name: common
    tasks_from: download.yml

- name : copy roboshop configuration
  ansible.builtin.template:
    src : roboshop.conf
    dest : /etc/nginx/default.d/roboshop.conf

- name : Start Nginx Service
  ansible.builtin.systemd:
    name : nginx
    state : restarted
    enabled : yes