
- name: Deleting old content
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: absent

- name: Download and Extract {{ COMPONENT }} Data
  ansible.builtin.unarchive:
    src: tps://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
    dest: /tmp
    remote_src: yes

