
- name: Deleting old content
  ansible.builtin.file:
    path: "{{ APP_LOCATION }}"
    state: absent

- name: Download and Extract {{ COMPONENT }} Data
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Copy {{ COMPONENT }} code to App location
  ansible.builtin.copy:
    src: /tmp/{{ COMPONENT }}-main/
    dest: "{{ APP_LOCATION}}/"
    remote_src: yes



